### ISSUE TITLE
check file length before plotting

### ISSUE THREAD

**Issue by xaratustrah** [xaratustrah/iqgui#2]
for IQT files, if the combination of the selected nframes and lframes are larger than there is data in the file, then the program will crash.

**Comment by nerdull** [comment]
Any remedies in this respect?

**Comment by xaratustrah** [comment]
This bug affects the IQT file format only which is very old and not used in the current experiments which uses TIQ file formats. But yes, I have to fix this in the GUI whenever there is more time. In the IQTools library it is not needed, because you can check before plotting.
