### ISSUE TITLE
Metadata is erroneously displayed

### ISSUE THREAD

**Issue by nerdull** [xaratustrah/iqgui#3]
I used iqgui to view a dummy file "238U_245_-2021.03.17.23.08.28.430.tiq" from the www file server.

However, some of the metadata is not correct, especially the span. It might be good to double check other entries as well.

<img width="209" alt="Screenshot 2021-05-03 162910" src="https://user-images.githubusercontent.com/8350980/116891585-2dfe1a00-ac2f-11eb-9c40-7e880365da0e.png">

**Comment by xaratustrah** [comment]
Hi and thanks. the information is taken directly from the XML file so they are basically correct. The span has no value in data analysis, so in future I can remove it from the dict.

**Comment by xaratustrah** [comment]
Just discovered the error to be the new XML data format for Tektronix files, the issue is resolved in the newest version [of iqtools library](https://github.com/xaratustrah/iqtools/tree/v2.2.1) on which iqgui depends.
