### ISSUE TITLE
Application crashes when starting frame exceeds a certain value

### ISSUE THREAD

**Issue by nerdull** [xaratustrah/iqgui#4]
This might be related to #3, but let us assume other entries in the File Info are correct.

For the same test file, it is supposed to be 60-second long. But when I set the _starting frame_ to be 30000, which corresponds to 19.66 seconds, provided that _points per frame_ are 1024, the Qt application crashes if click on the _Plot_ button. The _number of frames_ I try to plot is merely 200.

The error message is **ValueError: cannot reshape array of size 0 into shape (200,1024)**.

It works fine for small starting frame numbers.

**Comment by xaratustrah** [comment]
yes, the entries in the files are correct. yes, that is a similar issue. you must always care that there is enough "room" up there. This is a GUI only issue, just do not move the bar up there. This does not happen in the library.

**Comment by nerdull** [comment]
I'm a bit concerned that the application crashes even if there are still plenty of data left in the file.

**Comment by xaratustrah** [comment]
only if you choose the starting point such that the combination of lframes and nframes is larger than what is left, then it crashes. for now, you can avoid it by just deliberately not choosing a combination that goes over the edge. the GUI application is otherwise stable.

**Comment by xaratustrah** [comment]
after a current fix on the iqtools library this issue should not happen any more. This has been cured by proper error handling on the library level. in the IQGUI this will be captured in a try-except scope
