### ISSUE TITLE
Problem with float that should be int

### ISSUE THREAD

**Issue by DFreireF** [xaratustrah/iqgui#5]
@xaratustrah if you run iqgui.py:

> python iqgui.py
Traceback (most recent call last):
  File "/.../git/iqgui/iqgui.py", line 30, in <module>
    main()
  File "/.../git/iqgui/iqgui.py", line 24, in main
    form = mainWindow()
  File "...git/iqgui/mainwindow.py", line 71, in __init__
    self.verticalSlider_thld_max.setValue(1e6)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'`

So easy solution. 

It also throws some errors with the program running:
> qt.qpa.xcb: QXcbConnection: XCB error: 14 (BadIDChoice), sequence: 387, resource id: 1, major code: 53 (CreatePixmap), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 9 (BadDrawable), sequence: 388, resource id: 1, major code: 55 (CreateGC), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 9 (BadDrawable), sequence: 389, resource id: 1, major code: 72 (PutImage), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 13 (BadGC), sequence: 390, resource id: 56623113, major code: 60 (FreeGC), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 9 (BadDrawable), sequence: 391, resource id: 1, major code: 139 (Unknown), minor code: 4
qt.qpa.xcb: QXcbConnection: XCB error: 4 (BadPixmap), sequence: 392, resource id: 1, major code: 54 (FreePixmap), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 143 (Unknown), sequence: 393, resource id: 56623114, major code: 139 (Unknown), minor code: 27
qt.qpa.xcb: QXcbConnection: XCB error: 143 (Unknown), sequence: 394, resource id: 56623114, major code: 139 (Unknown), minor code: 7
qt.qpa.xcb: QXcbConnection: XCB error: 6 (BadCursor), sequence: 397, resource id: 56623115, major code: 138 (Unknown), minor code: 23
qt.qpa.xcb: QXcbConnection: XCB error: 6 (BadCursor), sequence: 398, resource id: 56623115, major code: 138 (Unknown), minor code: 23
qt.qpa.xcb: QXcbConnection: XCB error: 6 (BadCursor), sequence: 399, resource id: 56623115, major code: 2 (ChangeWindowAttributes), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 6 (BadCursor), sequence: 400, resource id: 56623115, major code: 2 (ChangeWindowAttributes), minor code: 0

Btw: It would be nice to have a package structure.

**Comment by xaratustrah** [comment]
solved as v2.5.7
